apiVersion: v1
kind: Pod
metadata:
  name: master-nginx
  labels:
    env: master-nginx
spec:
  containers:
  - name: nginx
    image: yousufquraishi/cloudethix_master_nginx_yousuf:v1
    ports:
    - containerPort: 80
